### ISSUE TITLE
Issue on page /docs/1. Install DeepProfiler.html

### ISSUE THREAD

**Issue by wongdanr** [cytomining/DeepProfiler-handbook#1]
Hello @rsenft1 I have tried installing DeepProfiler (both the docker version and installing from source) by following these instructions. I also download the example data as specified in 2.2, and set up an example project folder. In both the docker instance as well as from source, I am unable to get a working version of DeepProfiler. In particular, when I run the command:

python3 deepprofiler --root=/home/wongd26/JUMP1DeepProfiler/ --config config.json train

I get the following error: 

AttributeError: module 'plugins.models.resnet' has no attribute 'ModelClass'

Looking into plugins/models/resnet.py, I see that ModelClass is not explicitly defined as a class. 

Is this a bug? Or am installing incorrectly? Thank you for any help you can provide!

**Comment by rsenft1** [comment]
Hi! Thanks for making an issue (I see you're also on our slack so feel free to post there as I think you'll probably get feedback from a wider group there). 

Just so I understand, you're getting this issue with both the docker version and installing from source? 

And with both the JUMP experiment data as well as the more basic example we included?

**Comment by wongdanr** [comment]
Hi yes both docker and from source. Right now I'm just using the example data and configuration file provided. There's a thread on slack #ip-deepprofiler with details and full stack trace. Thanks!

**Comment by rsenft1** [comment]
migrated to #2
