### ISSUE TITLE
Example metadata references on page /docs/04-metadata.html

### ISSUE THREAD

**Issue by jccaicedo** [cytomining/DeepProfiler-handbook#14]
The metadata columns are explained in this chapter, and each column may have examples coming from the example data. 

@Arkkienkeli  Is it correct that the Treatment and Replicate are named `pert_name` and `pert_name_replicate` respectively?

If that is the case, please make a comment here and close the issue.

Thank you!

**Comment by Arkkienkeli** [comment]
Right, this different naming is explained in the chapter.
