### ISSUE TITLE
Order of sections - Issue on page /docs/05-config.html

### ISSUE THREAD

**Issue by jccaicedo** [cytomining/DeepProfiler-handbook#15]
We need to put the Profiling section before the Training section. This is going to be the trend for documentation in general.

We also need to reflect this in the actual config.json files. @Arkkienkeli can you put the Profiling section third, and the Training section fourth? Also, can you change the order in the example configuration file, and in all of our other configuration files that we plan to release?

**Comment by Arkkienkeli** [comment]
Reordered sections, let's keep this issue open until I upload configs.

**Comment by Arkkienkeli** [comment]
I have uploaded the configuration files to https://github.com/broadinstitute/DeepProfilerExperiments and added an additional subsection about those example configurations and how to get them.

**Comment by Arkkienkeli** [comment]
Todo: mention a config from example data.

**Comment by Arkkienkeli** [comment]
> Todo: mention a config from example data.

Done.

**Comment by jccaicedo** [comment]
This looks great!
