### ISSUE TITLE
Issue on page /docs/06-profiling.html[combinedset_cellsout_e30.hdf5]

### ISSUE THREAD

**Issue by semir2** [cytomining/DeepProfiler-handbook#19]
Hi,
Thanks for your great tool for cell painting, it helped me a lot. Now, I have a problem with combinedset_cellsout_e30.hdf5 file, could you provide this file for data processing(as you mentioned in your paper work)? 

Best

**Comment by Arkkienkeli** [comment]
Hello, thank you for the interest in our work!
We are going to release the models soon (most likely this week) and surely will provide the link in the documentation and in this issue.
I will keep this issue open until we release the models.

**Comment by Arkkienkeli** [comment]
@semir2 The model is now publicly availible, you can access it here: https://doi.org/10.5281/zenodo.7114558
