### ISSUE TITLE
Make clear how to name CSV files/ pathing info

### ISSUE THREAD

**Issue by rsenft1** [cytomining/DeepProfiler-handbook#2]
From [slack thread](https://broadinstitute.slack.com/archives/CPSCBNTNJ/p1650301451721349): 
Question: 
> How should the inputs/locations/ directory be organized? I couldn’t find any documentation on what the naming conventions should be for the CSV files (in order to link them with the right corresponding images), if CSVs should be separated by field or well, etc. Is there documentation somewhere? Thanks!

Solution: 
> locations path for an image is supposed to be locations/plate/well-site-Nuclei.csv

Make this more clear in documentation.

**Comment by jccaicedo** [comment]
The documentation of locations is currently entirely missing.
According to discussions in issue #6 we will add this information in Chapter 4 (Metadata). This seems to be assigned to @rsenft1 , but I believe she will need help from @Arkkienkeli to make sure the information is complete. I'm tagging you both so you can coordinate.

**Comment by jccaicedo** [comment]
This information is now available in Chapter 4!
